version: "2"
services:
  mysql:
    image: mariadb
    entrypoint: docker-entrypoint.sh --sql-mode='STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ports:
      - 3307:3306
    networks:
      - bridge
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mau
      - MYSQL_PASSWORD=123456
    volumes:
      - ./dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    networks:
      - bridge
    environment:
      PMA_HOST: mysql
networks: 
  bridge:
    driver: bridge
volumes:
  dbData: